import sampleResumeOne from '@/assets/soloman_energy.pdf';
import sampleResumeTwo from '@/assets/bell_n_harris.pdf';

import type { ApplicantRecord, FeedbackEntry } from './types';

const execRoster = ['Ava Patel', 'Mihika Rao', 'Isaiah Brooks', 'Laksh Shah'];

export const mockApplicants: ApplicantRecord[] = [
  {
    id: 9101,
    name: 'Gabriel Torres',
    email: 'gabriel.torres@illinois.edu',
    interest: 'I want to mentor underclassmen while contributing to process-heavy internal projects.',
    resume_filename: 'Gabriel_Torres_Resume.pdf',
    status: 'round_2',
    final_decision: 'PENDING',
    cycle_name: 'Cycle 2',
    created_at: '2026-03-21T11:05:00.000Z',
    reviewed_at: '2026-04-13T18:50:00.000Z',
    notes: 'Strong operator profile. Final round should test sharper synthesis.',
    has_assessment_link: true,
    assessment_completed: true,
    assessment_token: 'mock-gabriel-token',
    focus_loss_events: 0,
    is_flagged: false,
    integrity_notes: null,
    archived_at: null,
    assigned_exec: execRoster[0],
    resume_url: sampleResumeOne,
  },
  {
    id: 9102,
    name: 'Mina Kim',
    email: 'mina.kim@illinois.edu',
    interest: 'I want a selective team where execution quality and client presence both matter.',
    resume_filename: 'Mina_Kim_Resume.pdf',
    status: 'round_1',
    final_decision: 'PENDING',
    cycle_name: 'Cycle 2',
    created_at: '2026-04-01T12:30:00.000Z',
    reviewed_at: '2026-04-14T16:10:00.000Z',
    notes: 'Primary demo candidate for interviewer workspace testing.',
    has_assessment_link: true,
    assessment_completed: true,
    assessment_token: 'mock-mina-token',
    focus_loss_events: 0,
    is_flagged: false,
    integrity_notes: null,
    archived_at: null,
    assigned_exec: execRoster[1],
    resume_url: sampleResumeTwo,
  },
  {
    id: 9103,
    name: 'Omar Hassan',
    email: 'omar.hassan@illinois.edu',
    interest: 'I want more live-casing, tighter communication coaching, and a team with high standards.',
    resume_filename: 'Omar_Hassan_Resume.pdf',
    status: 'round_1',
    final_decision: 'PENDING',
    cycle_name: 'Cycle 1',
    created_at: '2026-03-31T10:40:00.000Z',
    reviewed_at: '2026-04-14T14:20:00.000Z',
    notes: 'Needs a clean read on quantitative structure.',
    has_assessment_link: false,
    assessment_completed: false,
    assessment_token: null,
    focus_loss_events: 0,
    is_flagged: false,
    integrity_notes: null,
    archived_at: null,
    assigned_exec: execRoster[2],
    resume_url: sampleResumeOne,
  },
  {
    id: 9104,
    name: 'Priya Nair',
    email: 'priya.nair@illinois.edu',
    interest: 'I want client-facing strategy work and a higher-ownership team environment.',
    resume_filename: 'Priya_Nair_Resume.pdf',
    status: 'round_2',
    final_decision: 'PENDING',
    cycle_name: 'Cycle 2',
    created_at: '2026-03-25T15:00:00.000Z',
    reviewed_at: '2026-04-13T12:45:00.000Z',
    notes: 'Advanced after a composed Round 1. Final round should push commercial judgment.',
    has_assessment_link: true,
    assessment_completed: true,
    assessment_token: 'mock-priya-token',
    focus_loss_events: 0,
    is_flagged: false,
    integrity_notes: null,
    archived_at: null,
    assigned_exec: execRoster[3],
    resume_url: sampleResumeTwo,
  },
];

export const mockFeedback: Record<number, FeedbackEntry[]> = {
  9101: [
    {
      id: 'feedback-gabriel-1',
      applicantId: 9101,
      applicantName: 'Gabriel Torres',
      interviewerName: 'Ethan Brooks',
      intervieweeName: 'Gabriel Torres',
      intervieweeGender: 'Other',
      interviewerRole: 'Primary',
      round: 'Round 1',
      leadershipScore: 3,
      interestInOtcrScore: 2,
      behavioralPerformanceScore: 3,
      businessAcumenScore: 2,
      qualitativeCreativityScore: 2,
      quantitativeStructureScore: 2,
      casePerformanceScore: 2,
      creativityConversationScore: 3,
      recommendation: 'YES',
      finalRoundSummary: 'Push on synthesis speed and how he handles sharper tradeoff pressure in the final round.',
      overallPerformanceOverview: 'YES. Experienced and polished with strong operational instincts. Felt client-ready for most of the discussion.',
      submittedAt: '2026-04-08T18:35:00.000Z',
    },
  ],
  9104: [
    {
      id: 'feedback-priya-1',
      applicantId: 9104,
      applicantName: 'Priya Nair',
      interviewerName: 'Maya Patel',
      intervieweeName: 'Priya Nair',
      intervieweeGender: 'Female',
      interviewerRole: 'Primary',
      round: 'Round 1',
      leadershipScore: 3,
      interestInOtcrScore: 3,
      behavioralPerformanceScore: 3,
      businessAcumenScore: 3,
      qualitativeCreativityScore: 2,
      quantitativeStructureScore: 3,
      casePerformanceScore: 3,
      creativityConversationScore: 3,
      recommendation: 'YES',
      finalRoundSummary: 'Final round should push deeper on business judgment and how she prioritizes under tighter ambiguity.',
      overallPerformanceOverview: 'YES. Clear move-forward candidate with polished communication and strong ownership examples.',
      submittedAt: '2026-04-07T19:30:00.000Z',
    },
    {
      id: 'feedback-priya-2',
      applicantId: 9104,
      applicantName: 'Priya Nair',
      interviewerName: 'Riya Shah',
      intervieweeName: 'Priya Nair',
      intervieweeGender: 'Female',
      interviewerRole: 'Secondary',
      round: 'Round 1',
      leadershipScore: 3,
      interestInOtcrScore: 3,
      behavioralPerformanceScore: 3,
      businessAcumenScore: 2,
      qualitativeCreativityScore: 2,
      quantitativeStructureScore: 3,
      casePerformanceScore: 3,
      creativityConversationScore: 3,
      recommendation: 'YES',
      finalRoundSummary: 'Would test tradeoffs and push for tighter prioritization in the next round.',
      overallPerformanceOverview: 'YES. Consistently strong candidate with thoughtful communication and real motivation for the organization.',
      submittedAt: '2026-04-07T19:42:00.000Z',
    },
  ],
};
