import sampleResumeOne from '@/assets/soloman_energy.pdf';
import sampleResumeTwo from '@/assets/bell_n_harris.pdf';

import type { ApplicantRecord, FeedbackEntry } from './types';

const execRoster = ['Ava Patel', 'Mihika Rao', 'Isaiah Brooks', 'Laksh Shah'];

export const mockApplicants: ApplicantRecord[] = [
  {
    id: 9001,
    name: 'Jordan Kim',
    email: 'jordan.kim@example.com',
    interest: 'Interested in healthcare ops, staffing systems, and turning ambiguous recruiting workflows into usable dashboards.',
    resume_filename: 'Jordan_Kim_Resume.pdf',
    status: 'pending',
    final_decision: 'MAYBE',
    cycle_name: 'Cycle 2',
    created_at: '2026-03-17T15:10:00.000Z',
    reviewed_at: null,
    notes: 'Strong resume. Wants to work on internal consulting operations.',
    has_assessment_link: false,
    assessment_completed: false,
    assessment_token: null,
    focus_loss_events: 0,
    is_flagged: false,
    integrity_notes: null,
    archived_at: null,
    assigned_exec: execRoster[0],
    resume_url: sampleResumeOne,
  },
  {
    id: 9002,
    name: 'Priya Nair',
    email: 'priya.nair@example.com',
    interest: 'Applied for consultant work focused on client strategy, workshop facilitation, and growth research.',
    resume_filename: 'Priya_Nair_Resume.pdf',
    status: 'approved',
    final_decision: 'YES',
    cycle_name: 'Cycle 1',
    created_at: '2026-03-12T11:45:00.000Z',
    reviewed_at: '2026-03-19T18:00:00.000Z',
    notes: 'Completed case prep with leadership team. Very polished.',
    has_assessment_link: true,
    assessment_completed: true,
    assessment_token: 'mock-priya-token',
    focus_loss_events: 0,
    is_flagged: false,
    integrity_notes: null,
    archived_at: null,
    assigned_exec: execRoster[1],
    resume_url: sampleResumeTwo,
  },
  {
    id: 9003,
    name: 'Marcus Chen',
    email: 'marcus.chen@example.com',
    interest: 'Interested in data analytics, process ops, and internal tooling for staffing and project planning.',
    resume_filename: null,
    status: 'pending',
    final_decision: 'MAYBE',
    cycle_name: 'Cycle 2',
    created_at: '2026-03-20T08:20:00.000Z',
    reviewed_at: null,
    notes: 'No resume uploaded yet. Referral from current member.',
    has_assessment_link: false,
    assessment_completed: false,
    assessment_token: null,
    focus_loss_events: 1,
    is_flagged: false,
    integrity_notes: null,
    archived_at: null,
    assigned_exec: execRoster[2],
    resume_url: null,
  },
  {
    id: 9004,
    name: 'Sofia Martinez',
    email: 'sofia.martinez@example.com',
    interest: 'Wants client-facing consultant experience and is specifically interested in strategy + operations engagements.',
    resume_filename: 'Sofia_Martinez_Resume.pdf',
    status: 'rejected',
    final_decision: 'NO',
    cycle_name: 'Cycle 1',
    created_at: '2026-03-08T13:35:00.000Z',
    reviewed_at: '2026-03-21T09:00:00.000Z',
    notes: 'Interview feedback leaned negative on ownership and structure.',
    has_assessment_link: false,
    assessment_completed: false,
    assessment_token: null,
    focus_loss_events: 2,
    is_flagged: true,
    integrity_notes: 'Two major focus changes during assessment practice.',
    archived_at: null,
    assigned_exec: execRoster[3],
    resume_url: sampleResumeOne,
  },
];

export const mockFeedback: Record<number, FeedbackEntry[]> = {
  9002: [
    {
      id: 'feedback-priya-1',
      applicantId: 9002,
      applicantName: 'Priya Nair',
      interviewerName: 'Adeetya Upadhyay',
      intervieweeName: 'Priya Nair',
      intervieweeGender: 'Female',
      interviewerRole: 'Primary',
      round: 'Round 1',
      leadershipScore: 3,
      interestInOtcrScore: 3,
      behavioralPerformanceScore: 3,
      businessAcumenScore: 3,
      qualitativeCreativityScore: 3,
      quantitativeStructureScore: 3,
      casePerformanceScore: 3,
      creativityConversationScore: 3,
      recommendation: 'YES',
      finalRoundSummary: 'Push her on depth of execution detail in the final round. She looks strong overall, but it would be useful to test how she handles more technical follow-through.',
      overallPerformanceOverview: 'YES. Clear communicator, strong client presence, and consistently structured under pressure. Feels polished and coachable.',
      submittedAt: '2026-03-20T17:00:00.000Z',
    },
  ],
  9004: [
    {
      id: 'feedback-sofia-1',
      applicantId: 9004,
      applicantName: 'Sofia Martinez',
      interviewerName: 'Aaron Liu',
      intervieweeName: 'Sofia Martinez',
      intervieweeGender: 'Female',
      interviewerRole: 'Primary',
      round: 'Round 1',
      leadershipScore: 1,
      interestInOtcrScore: 2,
      behavioralPerformanceScore: 2,
      businessAcumenScore: 1,
      qualitativeCreativityScore: 1,
      quantitativeStructureScore: 1,
      casePerformanceScore: 1,
      creativityConversationScore: 2,
      recommendation: 'NO',
      finalRoundSummary: 'N/A if obvious no. Main concern is structure under pressure and weak ownership examples. Final-round push points are already clear from the current interview.',
      overallPerformanceOverview: 'NO. Friendly and interested in the firm, but not ready this cycle. Responses stayed vague and the structure broke down when the case became ambiguous.',
      submittedAt: '2026-03-21T15:00:00.000Z',
    },
    {
      id: 'feedback-sofia-2',
      applicantId: 9004,
      applicantName: 'Sofia Martinez',
      interviewerName: 'Stuti Shah',
      intervieweeName: 'Sofia Martinez',
      intervieweeGender: 'Female',
      interviewerRole: 'Secondary',
      round: 'Round 1',
      leadershipScore: 1,
      interestInOtcrScore: 2,
      behavioralPerformanceScore: 2,
      businessAcumenScore: 1,
      qualitativeCreativityScore: 2,
      quantitativeStructureScore: 1,
      casePerformanceScore: 1,
      creativityConversationScore: 2,
      recommendation: 'NO',
      finalRoundSummary: 'N/A if obvious no. Concerns are already decisive: the interview did not show enough client-ready structure or specificity.',
      overallPerformanceOverview: 'NO. Positive energy, but the examples and casing structure were not concrete enough for client work. Recommend rejection.',
      submittedAt: '2026-03-21T16:00:00.000Z',
    },
  ],
};
