import sampleResumeOne from '@/assets/soloman_energy.pdf';
import sampleResumeTwo from '@/assets/bell_n_harris.pdf';

import type { ApplicantRecord, FeedbackEntry } from './types';

const execRoster = ['Ava Patel', 'Mihika Rao', 'Isaiah Brooks', 'Laksh Shah'];

export const mockApplicants: ApplicantRecord[] = [
  {
    id: 9001,
    name: 'Jordan Kim',
    email: 'jordan.kim@example.com',
    interest: 'Interested in healthcare ops, staffing systems, and turning ambiguous recruiting workflows into usable dashboards.',
    resume_filename: 'Jordan_Kim_Resume.pdf',
    status: 'pending',
    final_decision: 'MAYBE',
    cycle_name: 'Cycle 2',
    created_at: '2026-03-17T15:10:00.000Z',
    reviewed_at: null,
    notes: 'Strong resume. Wants to work on internal consulting operations.',
    has_assessment_link: false,
    assessment_completed: false,
    assessment_token: null,
    focus_loss_events: 0,
    is_flagged: false,
    integrity_notes: null,
    archived_at: null,
    assigned_exec: execRoster[0],
    resume_url: sampleResumeOne,
  },
  {
    id: 9002,
    name: 'Priya Nair',
    email: 'priya.nair@example.com',
    interest: 'Applied for consultant work focused on client strategy, workshop facilitation, and growth research.',
    resume_filename: 'Priya_Nair_Resume.pdf',
    status: 'approved',
    final_decision: 'YES',
    cycle_name: 'Cycle 1',
    created_at: '2026-03-12T11:45:00.000Z',
    reviewed_at: '2026-03-19T18:00:00.000Z',
    notes: 'Completed case prep with leadership team. Very polished.',
    has_assessment_link: true,
    assessment_completed: true,
    assessment_token: 'mock-priya-token',
    focus_loss_events: 0,
    is_flagged: false,
    integrity_notes: null,
    archived_at: null,
    assigned_exec: execRoster[1],
    resume_url: sampleResumeTwo,
  },
  {
    id: 9003,
    name: 'Marcus Chen',
    email: 'marcus.chen@example.com',
    interest: 'Interested in data analytics, process ops, and internal tooling for staffing and project planning.',
    resume_filename: null,
    status: 'pending',
    final_decision: 'MAYBE',
    cycle_name: 'Cycle 2',
    created_at: '2026-03-20T08:20:00.000Z',
    reviewed_at: null,
    notes: 'No resume uploaded yet. Referral from current member.',
    has_assessment_link: false,
    assessment_completed: false,
    assessment_token: null,
    focus_loss_events: 1,
    is_flagged: false,
    integrity_notes: null,
    archived_at: null,
    assigned_exec: execRoster[2],
    resume_url: null,
  },
  {
    id: 9004,
    name: 'Sofia Martinez',
    email: 'sofia.martinez@example.com',
    interest: 'Wants client-facing consultant experience and is specifically interested in strategy + operations engagements.',
    resume_filename: 'Sofia_Martinez_Resume.pdf',
    status: 'rejected',
    final_decision: 'NO',
    cycle_name: 'Cycle 1',
    created_at: '2026-03-08T13:35:00.000Z',
    reviewed_at: '2026-03-21T09:00:00.000Z',
    notes: 'Interview feedback leaned negative on ownership and structure.',
    has_assessment_link: false,
    assessment_completed: false,
    assessment_token: null,
    focus_loss_events: 2,
    is_flagged: true,
    integrity_notes: 'Two major focus changes during assessment practice.',
    archived_at: null,
    assigned_exec: execRoster[3],
    resume_url: sampleResumeOne,
  },
];

export const mockFeedback: Record<number, FeedbackEntry[]> = {
  9002: [
    {
      id: 'feedback-priya-1',
      applicantId: 9002,
      interviewerName: 'Adeetya Upadhyay',
      assignedExec: execRoster[1],
      round: 'Round 1',
      cultureFitScore: 5,
      technicalScore: 4,
      communicationScore: 5,
      leadershipPotentialScore: 4,
      recommendation: 'YES',
      strengths: 'Clear communicator, structured problem solving, strong client presence.',
      concerns: 'Could go deeper on technical implementation details.',
      comments: 'Would move forward. Feels highly coachable and polished.',
      submittedAt: '2026-03-20T17:00:00.000Z',
    },
  ],
  9004: [
    {
      id: 'feedback-sofia-1',
      applicantId: 9004,
      interviewerName: 'Aaron Liu',
      assignedExec: execRoster[3],
      round: 'Round 2',
      cultureFitScore: 2,
      technicalScore: 2,
      communicationScore: 3,
      leadershipPotentialScore: 2,
      recommendation: 'NO',
      strengths: 'Friendly and interested in the firm.',
      concerns: 'Weak structure under pressure; vague examples.',
      comments: 'Not ready this cycle.',
      submittedAt: '2026-03-21T15:00:00.000Z',
    },
    {
      id: 'feedback-sofia-2',
      applicantId: 9004,
      interviewerName: 'Stuti Shah',
      assignedExec: execRoster[3],
      round: 'Round 2',
      cultureFitScore: 3,
      technicalScore: 2,
      communicationScore: 3,
      leadershipPotentialScore: 2,
      recommendation: 'NO',
      strengths: 'Positive energy.',
      concerns: 'Responses were not concrete enough for client work.',
      comments: 'Recommend rejection.',
      submittedAt: '2026-03-21T16:00:00.000Z',
    },
  ],
};
