import {
  ApplicationStatus,
  InterviewRound,
  Role,
  type Applicant,
  type Assignment,
  type Evaluation,
  type RecruitingState,
  type RecruitingUser,
} from './types';

export const recruitingUsers: RecruitingUser[] = [
  { id: 'user-partner-maya', name: 'Maya Patel', email: 'maya.patel@otcr.org', role: Role.Partner, title: 'Partner', active: true },
  { id: 'user-partner-jonah', name: 'Jonah Reed', email: 'jonah.reed@otcr.org', role: Role.Partner, title: 'Partner', active: true },
  { id: 'user-pm-sana', name: 'Sana Ali', email: 'sana.ali@otcr.org', role: Role.PM, title: 'Project Manager', active: true },
  { id: 'user-pm-ethan', name: 'Ethan Brooks', email: 'ethan.brooks@otcr.org', role: Role.PM, title: 'Project Manager', active: true },
  { id: 'user-consultant-lila', name: 'Lila Chen', email: 'lila.chen@otcr.org', role: Role.Consultant, title: 'Consultant', active: true },
  { id: 'user-consultant-noah', name: 'Noah Kim', email: 'noah.kim@otcr.org', role: Role.Consultant, title: 'Consultant', active: true },
  { id: 'user-lc-riya', name: 'Riya Shah', email: 'riya.shah@otcr.org', role: Role.LC, title: 'Leadership Consultant', active: true },
  { id: 'user-lc-mateo', name: 'Mateo Gomez', email: 'mateo.gomez@otcr.org', role: Role.LC, title: 'Leadership Consultant', active: true },
];

export const applicants: Applicant[] = [
  {
    id: 'app-aanya-shah',
    name: 'Aanya Shah',
    email: 'aanya.shah@illinois.edu',
    resume: '/mock-resumes/aanya-shah.pdf',
    schoolYear: 'Sophomore',
    whyOtcr: 'I want client-facing training and exposure to structured problem solving early in college.',
    caseAnswer: 'I framed the problem around campus dining throughput, bottlenecks, and staffing utilization.',
    teamApplyingFor: 'Consulting',
    cycle: 1,
    status: ApplicationStatus.Applied,
    currentRound: null,
    finalDecision: 'pending',
    assignedPrimaryInterviewerId: null,
    assignedSecondaryInterviewerId: null,
    submittedAt: '2026-04-02T14:10:00.000Z',
    updatedAt: '2026-04-02T14:10:00.000Z',
    notes: 'Strong written motivation. Needs first-pass resume review.',
  },
  {
    id: 'app-daniel-park',
    name: 'Daniel Park',
    email: 'daniel.park@illinois.edu',
    resume: '/mock-resumes/daniel-park.pdf',
    schoolYear: 'Junior',
    whyOtcr: 'I want to build consulting fundamentals while working on recruiting and internal operations projects.',
    caseAnswer: 'I prioritized root-cause analysis for inconsistent volunteer onboarding and proposed a pilot workflow.',
    teamApplyingFor: 'Operations',
    cycle: 1,
    status: ApplicationStatus.Round1,
    currentRound: InterviewRound.Round1,
    finalDecision: 'pending',
    assignedPrimaryInterviewerId: 'user-pm-sana',
    assignedSecondaryInterviewerId: 'user-consultant-lila',
    submittedAt: '2026-03-29T17:22:00.000Z',
    updatedAt: '2026-04-04T19:40:00.000Z',
    notes: 'Resume and case response both solid. Ready for round 1.',
  },
  {
    id: 'app-emma-nguyen',
    name: 'Emma Nguyen',
    email: 'emma.nguyen@illinois.edu',
    resume: '/mock-resumes/emma-nguyen.pdf',
    schoolYear: 'Freshman',
    whyOtcr: 'I am looking for a steep learning environment with feedback-heavy interview prep and client work.',
    caseAnswer: 'I outlined how OTCR could improve recruiter response time using shared templates and better triage.',
    teamApplyingFor: 'Consulting',
    cycle: 2,
    status: ApplicationStatus.Round1,
    currentRound: InterviewRound.Round1,
    finalDecision: 'pending',
    assignedPrimaryInterviewerId: 'user-partner-jonah',
    assignedSecondaryInterviewerId: 'user-lc-riya',
    submittedAt: '2026-03-30T09:15:00.000Z',
    updatedAt: '2026-04-05T16:00:00.000Z',
    notes: 'Excellent energy. First-year candidate with upside.',
  },
  {
    id: 'app-farah-khan',
    name: 'Farah Khan',
    email: 'farah.khan@illinois.edu',
    resume: '/mock-resumes/farah-khan.pdf',
    schoolYear: 'Junior',
    whyOtcr: 'I want to sharpen case skills and work with peers who care about execution quality.',
    caseAnswer: 'I sized demand for late-night tutoring and built a simple supply-demand staffing recommendation.',
    teamApplyingFor: 'Consulting',
    cycle: 1,
    status: ApplicationStatus.Round2,
    currentRound: InterviewRound.Round2,
    finalDecision: 'pending',
    assignedPrimaryInterviewerId: 'user-partner-maya',
    assignedSecondaryInterviewerId: 'user-consultant-noah',
    submittedAt: '2026-03-22T13:40:00.000Z',
    updatedAt: '2026-04-08T15:15:00.000Z',
    notes: 'Advanced after a strong round 1. Needs pressure test in final round.',
  },
  {
    id: 'app-gabriel-torres',
    name: 'Gabriel Torres',
    email: 'gabriel.torres@illinois.edu',
    resume: '/mock-resumes/gabriel-torres.pdf',
    schoolYear: 'Senior',
    whyOtcr: 'I want to mentor underclassmen while contributing to process-heavy internal projects.',
    caseAnswer: 'I recommended segmenting applicant communications by stage and automating reminders.',
    teamApplyingFor: 'Internal',
    cycle: 2,
    status: ApplicationStatus.Round2,
    currentRound: InterviewRound.Round2,
    finalDecision: 'pending',
    assignedPrimaryInterviewerId: 'user-pm-ethan',
    assignedSecondaryInterviewerId: 'user-lc-mateo',
    submittedAt: '2026-03-21T11:05:00.000Z',
    updatedAt: '2026-04-09T18:50:00.000Z',
    notes: 'Experienced operator. Strong process instincts.',
  },
  {
    id: 'app-hana-choi',
    name: 'Hana Choi',
    email: 'hana.choi@illinois.edu',
    resume: '/mock-resumes/hana-choi.pdf',
    schoolYear: 'Sophomore',
    whyOtcr: 'The combination of client service, interview prep, and internal ownership is exactly what I want.',
    caseAnswer: 'I proposed standardizing project staffing requests through a weekly intake review.',
    teamApplyingFor: 'Technology',
    cycle: 1,
    status: ApplicationStatus.Accepted,
    currentRound: null,
    finalDecision: 'accepted',
    assignedPrimaryInterviewerId: 'user-partner-maya',
    assignedSecondaryInterviewerId: 'user-consultant-lila',
    submittedAt: '2026-03-18T16:45:00.000Z',
    updatedAt: '2026-04-10T20:10:00.000Z',
    notes: 'Accepted after strong final round and clear ownership signals.',
  },
  {
    id: 'app-isaac-lee',
    name: 'Isaac Lee',
    email: 'isaac.lee@illinois.edu',
    resume: '/mock-resumes/isaac-lee.pdf',
    schoolYear: 'Junior',
    whyOtcr: 'I want more live-case practice and a team that values strong feedback loops.',
    caseAnswer: 'I mapped causes of low event turnout and proposed segment-specific outreach experiments.',
    teamApplyingFor: 'Consulting',
    cycle: 2,
    status: ApplicationStatus.Rejected,
    currentRound: null,
    finalDecision: 'rejected',
    assignedPrimaryInterviewerId: 'user-pm-sana',
    assignedSecondaryInterviewerId: 'user-lc-riya',
    submittedAt: '2026-03-17T10:30:00.000Z',
    updatedAt: '2026-04-07T21:00:00.000Z',
    notes: 'Rejected after weak structure under follow-up pressure.',
  },
  {
    id: 'app-julia-bennett',
    name: 'Julia Bennett',
    email: 'julia.bennett@illinois.edu',
    resume: '/mock-resumes/julia-bennett.pdf',
    schoolYear: 'Graduate',
    whyOtcr: 'I bring prior research and operations experience and want a higher-ownership environment.',
    caseAnswer: 'I evaluated where recruiter handoffs fail and recommended clearer ownership checkpoints.',
    teamApplyingFor: 'Operations',
    cycle: 2,
    status: ApplicationStatus.Round1,
    currentRound: InterviewRound.Round1,
    finalDecision: 'pending',
    assignedPrimaryInterviewerId: 'user-partner-jonah',
    assignedSecondaryInterviewerId: 'user-consultant-noah',
    submittedAt: '2026-04-01T12:05:00.000Z',
    updatedAt: '2026-04-06T18:10:00.000Z',
    notes: 'Mature profile. Needs interview signal before advancing.',
  },
  {
    id: 'app-karan-mehta',
    name: 'Karan Mehta',
    email: 'karan.mehta@illinois.edu',
    resume: '/mock-resumes/karan-mehta.pdf',
    schoolYear: 'Senior',
    whyOtcr: 'I want a selective team where execution and communication both matter.',
    caseAnswer: 'I built a lightweight scoring model to prioritize follow-up with top recruiting leads.',
    teamApplyingFor: 'Consulting',
    cycle: 1,
    status: ApplicationStatus.Accepted,
    currentRound: null,
    finalDecision: 'accepted',
    assignedPrimaryInterviewerId: 'user-partner-maya',
    assignedSecondaryInterviewerId: 'user-lc-mateo',
    submittedAt: '2026-03-16T15:25:00.000Z',
    updatedAt: '2026-04-11T17:35:00.000Z',
    notes: 'Borderline early, then closed very strongly in final round.',
  },
  {
    id: 'app-leila-haddad',
    name: 'Leila Haddad',
    email: 'leila.haddad@illinois.edu',
    resume: '/mock-resumes/leila-haddad.pdf',
    schoolYear: 'Sophomore',
    whyOtcr: 'I want a collaborative place to improve business judgment and learn client communication.',
    caseAnswer: 'I suggested a phased recruiting funnel with manual reviewer calibration between stages.',
    teamApplyingFor: 'Design',
    cycle: 2,
    status: ApplicationStatus.Rejected,
    currentRound: null,
    finalDecision: 'rejected',
    assignedPrimaryInterviewerId: 'user-pm-ethan',
    assignedSecondaryInterviewerId: 'user-consultant-lila',
    submittedAt: '2026-03-20T14:55:00.000Z',
    updatedAt: '2026-04-05T14:05:00.000Z',
    notes: 'Good interest, but manual decision was rejection after inconsistent case performance.',
  },
];

export const assignments: Assignment[] = [
  {
    id: 'assign-daniel-r1-primary',
    applicantId: 'app-daniel-park',
    round: InterviewRound.Round1,
    role: 'primary',
    interviewerId: 'user-pm-sana',
    assignedByUserId: 'user-partner-maya',
    assignedAt: '2026-04-04T19:35:00.000Z',
  },
  {
    id: 'assign-daniel-r1-secondary',
    applicantId: 'app-daniel-park',
    round: InterviewRound.Round1,
    role: 'secondary',
    interviewerId: 'user-consultant-lila',
    assignedByUserId: 'user-partner-maya',
    assignedAt: '2026-04-04T19:36:00.000Z',
  },
  {
    id: 'assign-emma-r1-primary',
    applicantId: 'app-emma-nguyen',
    round: InterviewRound.Round1,
    role: 'primary',
    interviewerId: 'user-partner-jonah',
    assignedByUserId: 'user-pm-ethan',
    assignedAt: '2026-04-05T15:55:00.000Z',
  },
  {
    id: 'assign-emma-r1-secondary',
    applicantId: 'app-emma-nguyen',
    round: InterviewRound.Round1,
    role: 'secondary',
    interviewerId: 'user-lc-riya',
    assignedByUserId: 'user-pm-ethan',
    assignedAt: '2026-04-05T15:56:00.000Z',
  },
  {
    id: 'assign-farah-r2-primary',
    applicantId: 'app-farah-khan',
    round: InterviewRound.Round2,
    role: 'primary',
    interviewerId: 'user-partner-maya',
    assignedByUserId: 'user-partner-jonah',
    assignedAt: '2026-04-08T15:10:00.000Z',
  },
  {
    id: 'assign-farah-r2-secondary',
    applicantId: 'app-farah-khan',
    round: InterviewRound.Round2,
    role: 'secondary',
    interviewerId: 'user-consultant-noah',
    assignedByUserId: 'user-partner-jonah',
    assignedAt: '2026-04-08T15:11:00.000Z',
  },
  {
    id: 'assign-gabriel-r2-primary',
    applicantId: 'app-gabriel-torres',
    round: InterviewRound.Round2,
    role: 'primary',
    interviewerId: 'user-pm-ethan',
    assignedByUserId: 'user-partner-maya',
    assignedAt: '2026-04-09T18:45:00.000Z',
  },
  {
    id: 'assign-gabriel-r2-secondary',
    applicantId: 'app-gabriel-torres',
    round: InterviewRound.Round2,
    role: 'secondary',
    interviewerId: 'user-lc-mateo',
    assignedByUserId: 'user-partner-maya',
    assignedAt: '2026-04-09T18:46:00.000Z',
  },
];

export const evaluations: Evaluation[] = [
  {
    id: 'eval-daniel-r1-sana',
    applicantId: 'app-daniel-park',
    interviewerId: 'user-pm-sana',
    interviewerRole: Role.PM,
    round: InterviewRound.Round1,
    recommendation: 'yes',
    rubric: { communication: 4, structure: 4, problemSolving: 4, motivation: 5, teamwork: 4 },
    summary: 'Strong first round. Clear motivation and coachable problem-solving approach.',
    strengths: ['Good structure under moderate ambiguity', 'Convincing OTCR interest'],
    concerns: ['Needs tighter quantitative communication'],
    submittedAt: '2026-04-06T20:00:00.000Z',
  },
  {
    id: 'eval-emma-r1-jonah',
    applicantId: 'app-emma-nguyen',
    interviewerId: 'user-partner-jonah',
    interviewerRole: Role.Partner,
    round: InterviewRound.Round1,
    recommendation: 'lean_yes',
    rubric: { communication: 4, structure: 3, problemSolving: 3, motivation: 5, teamwork: 4 },
    summary: 'High upside. Early candidate but handled feedback well mid-case.',
    strengths: ['Strong energy', 'Coachability'],
    concerns: ['Light experience base', 'Needs sharper issue trees'],
    submittedAt: '2026-04-07T17:20:00.000Z',
  },
  {
    id: 'eval-farah-r1-noah',
    applicantId: 'app-farah-khan',
    interviewerId: 'user-consultant-noah',
    interviewerRole: Role.Consultant,
    round: InterviewRound.Round1,
    recommendation: 'yes',
    rubric: { communication: 4, structure: 5, problemSolving: 4, motivation: 4, teamwork: 4 },
    summary: 'Advanced comfortably from round 1 with strong structure and composure.',
    strengths: ['Very organized case approach', 'Calm under pushback'],
    concerns: ['Could be more hypothesis-driven earlier'],
    submittedAt: '2026-04-01T21:10:00.000Z',
  },
  {
    id: 'eval-gabriel-r1-ethan',
    applicantId: 'app-gabriel-torres',
    interviewerId: 'user-pm-ethan',
    interviewerRole: Role.PM,
    round: InterviewRound.Round1,
    recommendation: 'yes',
    rubric: { communication: 5, structure: 4, problemSolving: 4, motivation: 4, teamwork: 5 },
    summary: 'Experienced and polished. Strong operator profile.',
    strengths: ['Clear communication', 'Good operational instincts'],
    concerns: ['Could drive sharper synthesis at the end'],
    submittedAt: '2026-04-02T18:35:00.000Z',
  },
  {
    id: 'eval-hana-r2-maya',
    applicantId: 'app-hana-choi',
    interviewerId: 'user-partner-maya',
    interviewerRole: Role.Partner,
    round: InterviewRound.Round2,
    recommendation: 'strong_yes',
    rubric: { communication: 5, structure: 5, problemSolving: 5, motivation: 5, teamwork: 4 },
    summary: 'Offer-level candidate. Strong ownership and excellent client readiness.',
    strengths: ['Excellent synthesis', 'Clear ownership examples'],
    concerns: ['Slightly more reserved than peers'],
    submittedAt: '2026-04-10T19:30:00.000Z',
  },
  {
    id: 'eval-isaac-r1-riya',
    applicantId: 'app-isaac-lee',
    interviewerId: 'user-lc-riya',
    interviewerRole: Role.LC,
    round: InterviewRound.Round1,
    recommendation: 'no',
    rubric: { communication: 2, structure: 2, problemSolving: 2, motivation: 3, teamwork: 3 },
    summary: 'Interest was real, but execution and structure were below bar.',
    strengths: ['Positive attitude'],
    concerns: ['Weak structure', 'Limited specificity under follow-up'],
    submittedAt: '2026-04-03T16:40:00.000Z',
  },
  {
    id: 'eval-karan-r2-mateo',
    applicantId: 'app-karan-mehta',
    interviewerId: 'user-lc-mateo',
    interviewerRole: Role.LC,
    round: InterviewRound.Round2,
    recommendation: 'yes',
    rubric: { communication: 4, structure: 4, problemSolving: 5, motivation: 4, teamwork: 4 },
    summary: 'Closed well in the final round and showed much better synthesis than expected.',
    strengths: ['Strong analytics', 'Meaningful improvement'],
    concerns: ['Initial answers can still run long'],
    submittedAt: '2026-04-11T16:55:00.000Z',
  },
  {
    id: 'eval-leila-r1-lila',
    applicantId: 'app-leila-haddad',
    interviewerId: 'user-consultant-lila',
    interviewerRole: Role.Consultant,
    round: InterviewRound.Round1,
    recommendation: 'lean_no',
    rubric: { communication: 3, structure: 2, problemSolving: 2, motivation: 4, teamwork: 3 },
    summary: 'Good interest, but the case stayed shallow and manual decision ended in rejection.',
    strengths: ['Warm communication style'],
    concerns: ['Thin structure', 'Too generic on tradeoffs'],
    submittedAt: '2026-04-04T14:15:00.000Z',
  },
];

export const recruitingMockState: RecruitingState = {
  applicants,
  evaluations,
  assignments,
  users: recruitingUsers,
};
