import {
  ApplicationStatus,
  InterviewRound,
  Role,
  type Applicant,
  type Assignment,
  type Evaluation,
  type RecruitingState,
  type RecruitingUser,
} from './types';

export const recruitingUsers: RecruitingUser[] = [
  { id: 'user-partner-maya', name: 'Maya Patel', email: 'maya.patel@otcr.org', role: Role.Partner, title: 'Partner', active: true },
  { id: 'user-partner-jonah', name: 'Jonah Reed', email: 'jonah.reed@otcr.org', role: Role.Partner, title: 'Partner', active: true },
  { id: 'user-pm-sana', name: 'Sana Ali', email: 'sana.ali@otcr.org', role: Role.PM, title: 'Project Manager', active: true },
  { id: 'user-pm-ethan', name: 'Ethan Brooks', email: 'ethan.brooks@otcr.org', role: Role.PM, title: 'Project Manager', active: true },
  { id: 'user-consultant-lila', name: 'Lila Chen', email: 'lila.chen@otcr.org', role: Role.Consultant, title: 'Consultant', active: true },
  { id: 'user-consultant-noah', name: 'Noah Kim', email: 'noah.kim@otcr.org', role: Role.Consultant, title: 'Consultant', active: true },
  { id: 'user-lc-riya', name: 'Riya Shah', email: 'riya.shah@otcr.org', role: Role.LC, title: 'Leadership Consultant', active: true },
  { id: 'user-lc-mateo', name: 'Mateo Gomez', email: 'mateo.gomez@otcr.org', role: Role.LC, title: 'Leadership Consultant', active: true },
];

export const applicants: Applicant[] = [
  {
    id: 'app-aanya-shah',
    name: 'Aanya Shah',
    email: 'aanya.shah@illinois.edu',
    resume: '/mock-resumes/aanya-shah.pdf',
    schoolYear: 'Sophomore',
    whyOtcr: 'I want structured client work, sharper feedback loops, and more experience leading ambiguous projects.',
    caseAnswer: 'I framed the staffing issue around demand volatility, reviewer capacity, and a weekly allocation cadence.',
    teamApplyingFor: 'Consulting',
    cycle: 2,
    status: ApplicationStatus.Applied,
    currentRound: null,
    finalDecision: 'pending',
    assignedPrimaryInterviewerId: null,
    assignedSecondaryInterviewerId: null,
    submittedAt: '2026-04-02T13:15:00.000Z',
    updatedAt: '2026-04-02T13:15:00.000Z',
    notes: 'Fresh application. Waiting on initial screening.',
  },
  {
    id: 'app-daniel-park',
    name: 'Daniel Park',
    email: 'daniel.park@illinois.edu',
    resume: '/mock-resumes/daniel-park.pdf',
    schoolYear: 'Junior',
    whyOtcr: 'I want a team that cares about structured communication and operating discipline.',
    caseAnswer: 'I prioritized root causes for weak volunteer onboarding and proposed a weekly manager review.',
    teamApplyingFor: 'Operations',
    cycle: 1,
    status: ApplicationStatus.Round1,
    currentRound: InterviewRound.Round1,
    finalDecision: 'pending',
    assignedPrimaryInterviewerId: 'user-pm-sana',
    assignedSecondaryInterviewerId: 'user-consultant-lila',
    submittedAt: '2026-03-29T17:22:00.000Z',
    updatedAt: '2026-04-12T19:40:00.000Z',
    notes: 'Round 1 scheduled. Good written motivation.',
  },
  {
    id: 'app-emma-nguyen',
    name: 'Emma Nguyen',
    email: 'emma.nguyen@illinois.edu',
    resume: '/mock-resumes/emma-nguyen.pdf',
    schoolYear: 'Freshman',
    whyOtcr: 'I want steep coaching and real interview reps early in college.',
    caseAnswer: 'I outlined how OTCR could improve recruiter response time using better triage and templates.',
    teamApplyingFor: 'Consulting',
    cycle: 2,
    status: ApplicationStatus.Round1,
    currentRound: InterviewRound.Round1,
    finalDecision: 'pending',
    assignedPrimaryInterviewerId: 'user-partner-jonah',
    assignedSecondaryInterviewerId: 'user-lc-riya',
    submittedAt: '2026-03-30T09:15:00.000Z',
    updatedAt: '2026-04-12T17:05:00.000Z',
    notes: 'High upside candidate. Needs first-round signal.',
  },
  {
    id: 'app-gabriel-torres',
    name: 'Gabriel Torres',
    email: 'gabriel.torres@illinois.edu',
    resume: '/mock-resumes/gabriel-torres.pdf',
    schoolYear: 'Senior',
    whyOtcr: 'I want to mentor junior members while helping improve internal operations.',
    caseAnswer: 'I recommended segmenting applicant communications and automating reminders by stage.',
    teamApplyingFor: 'Internal',
    cycle: 2,
    status: ApplicationStatus.Round2,
    currentRound: InterviewRound.Round2,
    finalDecision: 'pending',
    assignedPrimaryInterviewerId: 'user-pm-ethan',
    assignedSecondaryInterviewerId: 'user-lc-mateo',
    submittedAt: '2026-03-21T11:05:00.000Z',
    updatedAt: '2026-04-13T18:50:00.000Z',
    notes: 'Strong operator profile. Final round should test sharper synthesis.',
  },
  {
    id: 'app-mina-kim',
    name: 'Mina Kim',
    email: 'mina.kim@illinois.edu',
    resume: '/mock-resumes/mina-kim.pdf',
    schoolYear: 'Junior',
    whyOtcr: 'I want a selective team where execution quality and client presence both matter.',
    caseAnswer: 'I built a two-phase recommendation for reducing recruiting handoff delays.',
    teamApplyingFor: 'Consulting',
    cycle: 2,
    status: ApplicationStatus.Round1,
    currentRound: InterviewRound.Round1,
    finalDecision: 'pending',
    assignedPrimaryInterviewerId: 'user-pm-ethan',
    assignedSecondaryInterviewerId: 'user-consultant-lila',
    submittedAt: '2026-04-01T12:30:00.000Z',
    updatedAt: '2026-04-14T16:10:00.000Z',
    notes: 'Primary demo candidate for interviewer workspace testing.',
  },
  {
    id: 'app-omar-hassan',
    name: 'Omar Hassan',
    email: 'omar.hassan@illinois.edu',
    resume: '/mock-resumes/omar-hassan.pdf',
    schoolYear: 'Senior',
    whyOtcr: 'I want more live-casing, tighter communication coaching, and a team with high standards.',
    caseAnswer: 'I sized demand for late-night tutoring and proposed a lighter staffing model.',
    teamApplyingFor: 'Consulting',
    cycle: 1,
    status: ApplicationStatus.Round1,
    currentRound: InterviewRound.Round1,
    finalDecision: 'pending',
    assignedPrimaryInterviewerId: 'user-pm-ethan',
    assignedSecondaryInterviewerId: 'user-consultant-noah',
    submittedAt: '2026-03-31T10:40:00.000Z',
    updatedAt: '2026-04-14T14:20:00.000Z',
    notes: 'Needs a clean read on quantitative structure.',
  },
  {
    id: 'app-priya-nair',
    name: 'Priya Nair',
    email: 'priya.nair@illinois.edu',
    resume: '/mock-resumes/priya-nair.pdf',
    schoolYear: 'Graduate',
    whyOtcr: 'I want client-facing strategy work and a higher-ownership team environment.',
    caseAnswer: 'I evaluated where recruiter handoffs fail and recommended clearer ownership checkpoints.',
    teamApplyingFor: 'Operations',
    cycle: 2,
    status: ApplicationStatus.Round2,
    currentRound: InterviewRound.Round2,
    finalDecision: 'pending',
    assignedPrimaryInterviewerId: 'user-partner-maya',
    assignedSecondaryInterviewerId: 'user-lc-riya',
    submittedAt: '2026-03-25T15:00:00.000Z',
    updatedAt: '2026-04-13T12:45:00.000Z',
    notes: 'Advanced after a composed Round 1. Final round should push commercial judgment.',
  },
  {
    id: 'app-zoe-martinez',
    name: 'Zoe Martinez',
    email: 'zoe.martinez@illinois.edu',
    resume: '/mock-resumes/zoe-martinez.pdf',
    schoolYear: 'Sophomore',
    whyOtcr: 'I want a collaborative place to build business judgment and communication confidence.',
    caseAnswer: 'I suggested a phased recruiting funnel with manual reviewer calibration between stages.',
    teamApplyingFor: 'Design',
    cycle: 2,
    status: ApplicationStatus.Round2,
    currentRound: InterviewRound.Round2,
    finalDecision: 'pending',
    assignedPrimaryInterviewerId: 'user-pm-ethan',
    assignedSecondaryInterviewerId: 'user-consultant-lila',
    submittedAt: '2026-03-27T14:55:00.000Z',
    updatedAt: '2026-04-14T11:05:00.000Z',
    notes: 'Balanced profile. Final round should test ownership and pace.',
  },
  {
    id: 'app-hana-choi',
    name: 'Hana Choi',
    email: 'hana.choi@illinois.edu',
    resume: '/mock-resumes/hana-choi.pdf',
    schoolYear: 'Sophomore',
    whyOtcr: 'The mix of client service, case prep, and real ownership is exactly what I want.',
    caseAnswer: 'I proposed standardizing project staffing requests through a weekly intake review.',
    teamApplyingFor: 'Technology',
    cycle: 1,
    status: ApplicationStatus.Accepted,
    currentRound: null,
    finalDecision: 'accepted',
    assignedPrimaryInterviewerId: 'user-partner-maya',
    assignedSecondaryInterviewerId: 'user-consultant-lila',
    submittedAt: '2026-03-18T16:45:00.000Z',
    updatedAt: '2026-04-10T20:10:00.000Z',
    notes: 'Accepted after strong final round and clear ownership signals.',
  },
  {
    id: 'app-isaac-lee',
    name: 'Isaac Lee',
    email: 'isaac.lee@illinois.edu',
    resume: '/mock-resumes/isaac-lee.pdf',
    schoolYear: 'Junior',
    whyOtcr: 'I want more live-case practice and a team that values strong feedback loops.',
    caseAnswer: 'I mapped causes of low event turnout and proposed segment-specific outreach experiments.',
    teamApplyingFor: 'Consulting',
    cycle: 2,
    status: ApplicationStatus.Rejected,
    currentRound: null,
    finalDecision: 'rejected',
    assignedPrimaryInterviewerId: 'user-pm-sana',
    assignedSecondaryInterviewerId: 'user-lc-riya',
    submittedAt: '2026-03-17T10:30:00.000Z',
    updatedAt: '2026-04-07T21:00:00.000Z',
    notes: 'Rejected after weak structure under follow-up pressure.',
  },
];

export const assignments: Assignment[] = [
  {
    id: 'assign-daniel-r1-primary',
    applicantId: 'app-daniel-park',
    round: InterviewRound.Round1,
    role: 'primary',
    interviewerId: 'user-pm-sana',
    assignedByUserId: 'user-partner-maya',
    assignedAt: '2026-04-11T19:35:00.000Z',
    room: 'Innovation 2A',
    scheduledTime: '2026-04-17T18:30',
  },
  {
    id: 'assign-daniel-r1-secondary',
    applicantId: 'app-daniel-park',
    round: InterviewRound.Round1,
    role: 'secondary',
    interviewerId: 'user-consultant-lila',
    assignedByUserId: 'user-partner-maya',
    assignedAt: '2026-04-11T19:36:00.000Z',
    room: 'Innovation 2A',
    scheduledTime: '2026-04-17T18:30',
  },
  {
    id: 'assign-emma-r1-primary',
    applicantId: 'app-emma-nguyen',
    round: InterviewRound.Round1,
    role: 'primary',
    interviewerId: 'user-partner-jonah',
    assignedByUserId: 'user-pm-ethan',
    assignedAt: '2026-04-12T15:55:00.000Z',
    room: 'North Interview Pod',
    scheduledTime: '2026-04-18T17:00',
  },
  {
    id: 'assign-emma-r1-secondary',
    applicantId: 'app-emma-nguyen',
    round: InterviewRound.Round1,
    role: 'secondary',
    interviewerId: 'user-lc-riya',
    assignedByUserId: 'user-pm-ethan',
    assignedAt: '2026-04-12T15:56:00.000Z',
    room: 'North Interview Pod',
    scheduledTime: '2026-04-18T17:00',
  },
  {
    id: 'assign-gabriel-r2-primary',
    applicantId: 'app-gabriel-torres',
    round: InterviewRound.Round2,
    role: 'primary',
    interviewerId: 'user-pm-ethan',
    assignedByUserId: 'user-partner-maya',
    assignedAt: '2026-04-13T18:45:00.000Z',
    room: 'War Room B',
    scheduledTime: '2026-04-19T19:15',
  },
  {
    id: 'assign-gabriel-r2-secondary',
    applicantId: 'app-gabriel-torres',
    round: InterviewRound.Round2,
    role: 'secondary',
    interviewerId: 'user-lc-mateo',
    assignedByUserId: 'user-partner-maya',
    assignedAt: '2026-04-13T18:46:00.000Z',
    room: 'War Room B',
    scheduledTime: '2026-04-19T19:15',
  },
  {
    id: 'assign-mina-r1-primary',
    applicantId: 'app-mina-kim',
    round: InterviewRound.Round1,
    role: 'primary',
    interviewerId: 'user-pm-ethan',
    assignedByUserId: 'user-partner-jonah',
    assignedAt: '2026-04-14T16:00:00.000Z',
    room: 'North Pod 3',
    scheduledTime: '2026-04-20T18:00',
  },
  {
    id: 'assign-mina-r1-secondary',
    applicantId: 'app-mina-kim',
    round: InterviewRound.Round1,
    role: 'secondary',
    interviewerId: 'user-consultant-lila',
    assignedByUserId: 'user-partner-jonah',
    assignedAt: '2026-04-14T16:01:00.000Z',
    room: 'North Pod 3',
    scheduledTime: '2026-04-20T18:00',
  },
  {
    id: 'assign-omar-r1-primary',
    applicantId: 'app-omar-hassan',
    round: InterviewRound.Round1,
    role: 'primary',
    interviewerId: 'user-pm-ethan',
    assignedByUserId: 'user-partner-maya',
    assignedAt: '2026-04-14T14:10:00.000Z',
    room: 'Case Room 1',
    scheduledTime: '2026-04-21T17:30',
  },
  {
    id: 'assign-omar-r1-secondary',
    applicantId: 'app-omar-hassan',
    round: InterviewRound.Round1,
    role: 'secondary',
    interviewerId: 'user-consultant-noah',
    assignedByUserId: 'user-partner-maya',
    assignedAt: '2026-04-14T14:11:00.000Z',
    room: 'Case Room 1',
    scheduledTime: '2026-04-21T17:30',
  },
  {
    id: 'assign-priya-r2-primary',
    applicantId: 'app-priya-nair',
    round: InterviewRound.Round2,
    role: 'primary',
    interviewerId: 'user-partner-maya',
    assignedByUserId: 'user-pm-sana',
    assignedAt: '2026-04-13T12:35:00.000Z',
    room: 'Exec Room',
    scheduledTime: '2026-04-18T19:00',
  },
  {
    id: 'assign-priya-r2-secondary',
    applicantId: 'app-priya-nair',
    round: InterviewRound.Round2,
    role: 'secondary',
    interviewerId: 'user-lc-riya',
    assignedByUserId: 'user-pm-sana',
    assignedAt: '2026-04-13T12:36:00.000Z',
    room: 'Exec Room',
    scheduledTime: '2026-04-18T19:00',
  },
  {
    id: 'assign-zoe-r2-primary',
    applicantId: 'app-zoe-martinez',
    round: InterviewRound.Round2,
    role: 'primary',
    interviewerId: 'user-pm-ethan',
    assignedByUserId: 'user-partner-jonah',
    assignedAt: '2026-04-14T11:00:00.000Z',
    room: 'War Room A',
    scheduledTime: '2026-04-22T18:15',
  },
  {
    id: 'assign-zoe-r2-secondary',
    applicantId: 'app-zoe-martinez',
    round: InterviewRound.Round2,
    role: 'secondary',
    interviewerId: 'user-consultant-lila',
    assignedByUserId: 'user-partner-jonah',
    assignedAt: '2026-04-14T11:01:00.000Z',
    room: 'War Room A',
    scheduledTime: '2026-04-22T18:15',
  },
];

export const evaluations: Evaluation[] = [
  {
    id: 'eval-daniel-r1-sana',
    applicantId: 'app-daniel-park',
    interviewerId: 'user-pm-sana',
    interviewerRole: Role.PM,
    round: InterviewRound.Round1,
    recommendation: 'yes',
    rubric: { communication: 4, structure: 4, problemSolving: 4, motivation: 5, teamwork: 4 },
    summary: 'Strong first round. Clear motivation and coachable problem-solving approach.',
    strengths: ['Good structure under moderate ambiguity', 'Convincing OTCR interest'],
    concerns: ['Needs tighter quantitative communication'],
    submittedAt: '2026-04-12T20:00:00.000Z',
  },
  {
    id: 'eval-daniel-r1-lila',
    applicantId: 'app-daniel-park',
    interviewerId: 'user-consultant-lila',
    interviewerRole: Role.Consultant,
    round: InterviewRound.Round1,
    recommendation: 'lean_yes',
    rubric: { communication: 4, structure: 3, problemSolving: 3, motivation: 4, teamwork: 4 },
    summary: 'Positive round-one signal with good coachability and solid communication.',
    strengths: ['Warm presence', 'Took hints well'],
    concerns: ['Math communication still needs discipline'],
    submittedAt: '2026-04-12T20:18:00.000Z',
  },
  {
    id: 'eval-emma-r1-jonah',
    applicantId: 'app-emma-nguyen',
    interviewerId: 'user-partner-jonah',
    interviewerRole: Role.Partner,
    round: InterviewRound.Round1,
    recommendation: 'lean_yes',
    rubric: { communication: 4, structure: 3, problemSolving: 3, motivation: 5, teamwork: 4 },
    summary: 'High upside. Early candidate but handled feedback well mid-case.',
    strengths: ['Strong energy', 'Coachability'],
    concerns: ['Needs sharper issue trees'],
    submittedAt: '2026-04-12T17:20:00.000Z',
  },
  {
    id: 'eval-gabriel-r1-ethan',
    applicantId: 'app-gabriel-torres',
    interviewerId: 'user-pm-ethan',
    interviewerRole: Role.PM,
    round: InterviewRound.Round1,
    recommendation: 'yes',
    rubric: { communication: 5, structure: 4, problemSolving: 4, motivation: 4, teamwork: 5 },
    summary: 'Experienced and polished. Strong operator profile.',
    strengths: ['Clear communication', 'Good operational instincts'],
    concerns: ['Could drive sharper synthesis at the end'],
    submittedAt: '2026-04-08T18:35:00.000Z',
  },
  {
    id: 'eval-gabriel-r1-mateo',
    applicantId: 'app-gabriel-torres',
    interviewerId: 'user-lc-mateo',
    interviewerRole: Role.LC,
    round: InterviewRound.Round1,
    recommendation: 'lean_yes',
    rubric: { communication: 4, structure: 4, problemSolving: 4, motivation: 4, teamwork: 4 },
    summary: 'Strong round-one close. Mature answers and good presence.',
    strengths: ['Stable under pushback', 'Good polish'],
    concerns: ['Should synthesize faster'],
    submittedAt: '2026-04-08T18:50:00.000Z',
  },
  {
    id: 'eval-priya-r1-maya',
    applicantId: 'app-priya-nair',
    interviewerId: 'user-partner-maya',
    interviewerRole: Role.Partner,
    round: InterviewRound.Round1,
    recommendation: 'yes',
    rubric: { communication: 4, structure: 4, problemSolving: 4, motivation: 5, teamwork: 4 },
    summary: 'Clear move-forward candidate with polished communication and strong ownership examples.',
    strengths: ['Very composed', 'Good executive presence'],
    concerns: ['Final round should push business judgment harder'],
    submittedAt: '2026-04-07T19:30:00.000Z',
  },
  {
    id: 'eval-priya-r1-riya',
    applicantId: 'app-priya-nair',
    interviewerId: 'user-lc-riya',
    interviewerRole: Role.LC,
    round: InterviewRound.Round1,
    recommendation: 'yes',
    rubric: { communication: 4, structure: 4, problemSolving: 3, motivation: 5, teamwork: 4 },
    summary: 'Consistently strong candidate. Advanced comfortably after round one.',
    strengths: ['Thoughtful communication', 'Strong motivation'],
    concerns: ['Would probe tradeoffs more deeply in final round'],
    submittedAt: '2026-04-07T19:42:00.000Z',
  },
  {
    id: 'eval-hana-r2-maya',
    applicantId: 'app-hana-choi',
    interviewerId: 'user-partner-maya',
    interviewerRole: Role.Partner,
    round: InterviewRound.Round2,
    recommendation: 'strong_yes',
    rubric: { communication: 5, structure: 5, problemSolving: 5, motivation: 5, teamwork: 4 },
    summary: 'Offer-level candidate. Strong ownership and excellent client readiness.',
    strengths: ['Excellent synthesis', 'Clear ownership examples'],
    concerns: ['Slightly more reserved than peers'],
    submittedAt: '2026-04-10T19:30:00.000Z',
  },
  {
    id: 'eval-isaac-r1-riya',
    applicantId: 'app-isaac-lee',
    interviewerId: 'user-lc-riya',
    interviewerRole: Role.LC,
    round: InterviewRound.Round1,
    recommendation: 'no',
    rubric: { communication: 2, structure: 2, problemSolving: 2, motivation: 3, teamwork: 3 },
    summary: 'Interest was real, but execution and structure were below bar.',
    strengths: ['Positive attitude'],
    concerns: ['Weak structure', 'Limited specificity under follow-up'],
    submittedAt: '2026-04-03T16:40:00.000Z',
  },
];

export const recruitingMockState: RecruitingState = {
  applicants,
  evaluations,
  assignments,
  users: recruitingUsers,
};
